const GET_DOG_IMAGE = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  REQUEST: 'GET_DOG_IMAGE_REQUEST',
  SUCCESS: 'GET_DOG_IMAGE_SUCCESS',
  ERROR: 'GET_DOG_IMAGE_ERROR',
  LOGIN: 'LOGIN',
  CALCULATE: 'CALCULATE',
  SECONDNUM: 'SECONDNUM',
  ENTER: 'ENTER',
};

export default {
  GET_DOG_IMAGE,
};
